AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31

Description: 'Template of infraestructure for serverless web demo'
    
Resources:

  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: "${AWS::StackName}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: 
              Fn::GetAtt: SiteBucket.DomainName
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: "true"
        Comment: 
          Fn::Join: [".", [Ref: AWS::StackName, "Distribution"]]
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          Compress: True
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Identity to access site for surftc.comercios.co"
Outputs:
  CloudFrontDistributionOutput:
    Description: CloudFront Distribution
    Value: 
      Ref: CloudFrontDistribution
    Export:
      Name: 
        Fn::Join: ["-", [Ref: AWS::StackName, "PortalDistribution"]]